spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:tcp://localhost/~/withpet

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 500
        #        show_sql: true
        format_sql: true
        use_sql_comments: false
    show-sql: true
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug

