data:
  animal-protect:
    url: http://openapi.animal.go.kr/openapi/service/rest/abandonmentPublicSrvc
    service-key: b7ku%2FeMJ9krV5c3CyhANG3bnLBBGoa1LzziE5qIrv%2Bso0yM%2Bmu7PUyLyD%2F8cCFqUw2nD17XSjs4kJjjRvu%2Fh9A%3D%3D
  animal-shelter:
    url: http://api.data.go.kr/openapi/tn_pubr_public_animal_cnter_api
    service-key: b7ku%2FeMJ9krV5c3CyhANG3bnLBBGoa1LzziE5qIrv%2Bso0yM%2Bmu7PUyLyD%2F8cCFqUw2nD17XSjs4kJjjRvu%2Fh9A%3D%3D
  kakao:
    url: http://dapi.kakao.com
    rest-api-key: KakaoAK 2c95d7e9ccdaa752fba36a7003ffce3d
  v-world-address:
    url: http://api.vworld.kr/req/search
    service-key: 442B9BB4-EE2B-3C47-967E-B43C9ECD8500

aws:
  s3:
    endPoint: https://kr.object.ncloudstorage.com
    regionName: kr-standard
    bucketName: withpet-bucket
    access-key: 7XvoRYLkyCWNxTJZgNx2
    secret-key:
    prefix-url: https://kr.object.ncloudstorage.com/