data:
  animal-protect:
    url: http://openapi.animal.go.kr/openapi/service/rest/abandonmentPublicSrvc
    service-key: b7ku%2FeMJ9krV5c3CyhANG3bnLBBGoa1LzziE5qIrv%2Bso0yM%2Bmu7PUyLyD%2F8cCFqUw2nD17XSjs4kJjjRvu%2Fh9A%3D%3D
  kakao:
    url: http://dapi.kakao.com
    rest-api-key: KakaoAK 2c95d7e9ccdaa752fba36a7003ffce3d